apiVersion: v1
kind: Pod
metadata:
  name: affinity-nodeselector
  labels:
    app: web 
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity: 
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: instance
            operator: In 
            values:
            - worker1
          