apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    app: jenkins 
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins
    ports:
    - containerPort: 8080
  affinity:
    podAntiAffinity: 
      requiredDuringSchedulingIgnoreDuringExecution:
        labelSelector:
        - matchExpressions:
          - key: app
            operator: In 
            values:
            - web
        topologyKey: kubernetes.io/hostname
          