apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: nginx-daemon
  labels:
    app: nginx
spec: 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    containers:
    - name: nginx-daemon
      image: nginx:1.20
      ports:
      - containerPort: 80