apiVersion: v1
kind: Pod
metadata:
  name: golang
  namespace: prashant
  labels:
    app: alpine
spec:
  containers:
  - name: golang-secret
    image: golang:alpine3.14
    command: ["sleep","10000"]
    env:
    - name: DBNAME
      valueFrom:
        configMapKeyRef:
          name: database-name
          key: db-name
    - name: DBPASSWORD
      valueFrom:
        secretKeyRef:
          name: database-password
          key: db-pass