apiVersion: v1
kind: Pod
metadata:
  name: nodeselector
  labels:
    app: web 
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
  nodeSelector:
    instance: worker1 