apiVersion: v1
kind: Pod
metadata:
  name: nodeslector
  labels:
    app: web
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
    resources: 
      requests: 
        cpu: 0.25
        memory: "128Mi"
      limits:
        cpu: 0.5
        memory: "256Mi"
