apiVersion: v1
kind: Pod
metadata: 
  name: nginx 
  labels:
    app: nginx
spec:
  volumes:
  - name: nginx-volume
    persistentVolumeClaim: 
      claimName: pv-claim
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80